apiVersion: 1

datasources:
  - name: Graphite
    type: graphite
    access: proxy
    url: "http://graphite:80"
    user: root
    secureJsonData:
      password: root
    jsonData:
      graphiteVersion: '1.1'