apiVersion: v1
kind: Service
metadata:
  name: user-microservice-service
spec:
  type: NodePort
  selector:
    app: user-microservice
  ports:
    # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 3500
      targetPort: 3500
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007