version: '3.7'
services:
  credentials-audit-database:
    image: mongo:6.0.2
    container_name: credentials-audit-database
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo-user-admin
      MONGO_INITDB_ROOT_PASSWORD: mongo-password-admin
      MONGO_CREDENTIAL_SERVICE_USERNAME: mongo-user-credential-service
      MONGO_CREDENTIAL_SERVICE_PASSWORD: mongo-password-credential-service
      MONGO_CREDENTIAL_SERVICE_DB: mongo-db-credential-service
      MONGO_INITDB_DATABASE: mongo-db-credential-service
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh