#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE DATABASE "$CREDENTIAL_PLATFORM_DB";

  CREATE SCHEMA "$SECURITY_PROVIDER_SCHEMA";
  CREATE USER "$SECURITY_PROVIDER_USER" WITH PASSWORD '$SECURITY_PROVIDER_PASSWORD';
  GRANT USAGE ON SCHEMA "$SECURITY_PROVIDER_SCHEMA" TO "$SECURITY_PROVIDER_USER";

  CREATE SCHEMA "$CREDENTIAL_MICROSERVICE_SCHEMA";
  CREATE USER "$CREDENTIAL_MICROSERVICE_USER" WITH PASSWORD '$CREDENTIAL_MICROSERVICE_PASSWORD';
  GRANT USAGE ON SCHEMA "$CREDENTIAL_MICROSERVICE_SCHEMA" TO "$CREDENTIAL_MICROSERVICE_USER";

EOSQL


psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$CREDENTIAL_PLATFORM_DB" <<-EOSQL

  CREATE SCHEMA "$SECURITY_PROVIDER_SCHEMA";
  GRANT USAGE ON SCHEMA "$SECURITY_PROVIDER_SCHEMA" TO "$SECURITY_PROVIDER_USER";
  GRANT ALL ON SCHEMA "$SECURITY_PROVIDER_SCHEMA" TO "$SECURITY_PROVIDER_USER";

  CREATE SCHEMA "$CREDENTIAL_MICROSERVICE_SCHEMA";
  GRANT USAGE ON SCHEMA "$CREDENTIAL_MICROSERVICE_SCHEMA" TO "$CREDENTIAL_MICROSERVICE_USER";
  GRANT ALL ON SCHEMA "$CREDENTIAL_MICROSERVICE_SCHEMA" TO "$CREDENTIAL_MICROSERVICE_USER";
EOSQL