#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER "$KEYCLOAK_USER" WITH PASSWORD '$KEYCLOAK_PASSWORD';
  CREATE DATABASE "$KEYCLOAK_DB";
  GRANT ALL PRIVILEGES ON DATABASE "$KEYCLOAK_DB" TO "$KEYCLOAK_USER";
EOSQL