apiVersion: v1
kind: Service
metadata:
  labels:
    app: general-service
  name: general-service-122
  namespace: default
spec:
  ports:
    - port: 8889
      protocol: TCP
  type: NodePort
  selector:
    app: general-service
