version: '3.7'
services:
  credentials-audit-database:
    image: mongo:6.0.2
    container_name: credentials-audit-database
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: credentials-user
      MONGO_INITDB_ROOT_PASSWORD: credentials-password
    ports:
      - "27017:27017"